services:
  postgres:
    image: postgres:16
    container_name: jobtrail-postgres
    environment:
      POSTGRES_DB: jobtrail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - jobtrail_postgres_data:/var/lib/postgresql/data

volumes:
  jobtrail_postgres_data:
