CREATE TABLE applications
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    company_id       BIGINT                                  NOT NULL,
    position_title   VARCHAR(255)                            NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    application_date date,
    job_url          VARCHAR(255),
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_applications PRIMARY KEY (id)
);

CREATE TABLE companies
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    website  VARCHAR(255),
    location VARCHAR(255),
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE applications
    ADD CONSTRAINT uc_applications_user_company_position UNIQUE (user_id, company_id, position_title);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE companies
    ADD CONSTRAINT FK_COMPANIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_id_user
        UNIQUE (id, user_id);

ALTER TABLE applications
    ADD CONSTRAINT fk_applications_company_user
        FOREIGN KEY (company_id, user_id)
            REFERENCES companies (id, user_id);
