CREATE TABLE profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_role         VARCHAR(100)                            NOT NULL,
    location_preference VARCHAR(100)                            NOT NULL,
    availability        VARCHAR(100)                            NOT NULL,
    experience_level    VARCHAR(255)                            NOT NULL,
    summary             VARCHAR(2000),
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

ALTER TABLE users
    ADD profile_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT uc_users_profile UNIQUE (profile_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_profile FOREIGN KEY (profile_id) REFERENCES profiles (id);

CREATE TABLE profile_skills
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id    BIGINT                                  NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    level         VARCHAR(255)                            NOT NULL,
    is_main_skill BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_profile_skills PRIMARY KEY (id),
    CONSTRAINT fk_profile_skills_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE profile_languages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id BIGINT                                  NOT NULL,
    language   VARCHAR(50)                             NOT NULL,
    level      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_profile_languages PRIMARY KEY (id),
    CONSTRAINT fk_profile_languages_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE profile_projects
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id  BIGINT                                  NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(2000),
    CONSTRAINT pk_profile_projects PRIMARY KEY (id),
    CONSTRAINT fk_profile_projects_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE profile_project_technologies
(
    project_id BIGINT       NOT NULL,
    technology VARCHAR(100) NOT NULL,
    CONSTRAINT fk_profile_project_technologies_project
        FOREIGN KEY (project_id) REFERENCES profile_projects (id)
);

CREATE TABLE profile_preferred_roles
(
    profile_id BIGINT       NOT NULL,
    role       VARCHAR(255) NOT NULL,
    CONSTRAINT fk_profile_preferred_roles_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE TABLE profile_avoid_keywords
(
    profile_id BIGINT       NOT NULL,
    keyword    VARCHAR(255) NOT NULL,
    CONSTRAINT fk_profile_avoid_keywords_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);
