CREATE TABLE application_status_history
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application_id    BIGINT                                  NOT NULL,
    previous_status   VARCHAR(255),
    new_status        VARCHAR(255)                             NOT NULL,
    changed_at        TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_application_status_history PRIMARY KEY (id),
    CONSTRAINT fk_status_history_application
        FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE
);

CREATE INDEX idx_status_history_application_changed
    ON application_status_history (application_id, changed_at, id);

INSERT INTO application_status_history (application_id, previous_status, new_status, changed_at)
SELECT id, NULL, status, created_at
FROM applications;
